### ISSUE TITLE
PG::UndefinedFunction: ERROR:  function ifnull(numeric, numeric) does not exist

### ISSUE THREAD

**Issue by deepakm-webonise** [vinsol-spree-contrib/spree-admin-insights#22]
```
Sequel::DatabaseError (PG::UndefinedFunction: ERROR:  function ifnull(numeric, numeric) does not exist
LINE 1: ...ent", 0 AS "promotion_discount" FROM (SELECT SUM((IFNULL("li...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
):
  sequel (4.32.0) lib/sequel/adapters/postgres.rb:186:in `async_exec'
  sequel (4.32.0) lib/sequel/adapters/postgres.rb:186:in `block in execute_query'
  sequel (4.32.0) lib/sequel/database/logging.rb:35:in `log_yield'
  sequel (4.32.0) lib/sequel/adapters/postgres.rb:186:in `execute_query'
  sequel (4.32.0) lib/sequel/adapters/postgres.rb:173:in `block in execute'
  sequel (4.32.0) lib/sequel/adapters/postgres.rb:149:in `check_disconnect_errors'
  sequel (4.32.0) lib/sequel/adapters/postgres.rb:173:in `execute'
  sequel (4.32.0) lib/sequel/adapters/postgres.rb:525:in `_execute'
  sequel (4.32.0) lib/sequel/adapters/postgres.rb:341:in `block (2 levels) in execute'
  sequel (4.32.0) lib/sequel/adapters/postgres.rb:546:in `check_database_errors'
  sequel (4.32.0) lib/sequel/adapters/postgres.rb:341:in `block in execute'
  sequel (4.32.0) lib/sequel/database/connecting.rb:251:in `block in synchronize'
  sequel (4.32.0) lib/sequel/connection_pool/threaded.rb:105:in `hold'
  sequel (4.32.0) lib/sequel/database/connecting.rb:251:in `synchronize'
  sequel (4.32.0) lib/sequel/adapters/postgres.rb:341:in `execute'
  sequel (4.32.0) lib/sequel/dataset/actions.rb:952:in `execute'
  sequel (4.32.0) lib/sequel/adapters/postgres.rb:669:in `fetch_rows'
  sequel (4.32.0) lib/sequel/dataset/actions.rb:141:in `each'
  sequel (4.32.0) lib/sequel/dataset/actions.rb:47:in `block in all'
  sequel (4.32.0) lib/sequel/dataset/actions.rb:892:in `_all'
  sequel (4.32.0) lib/sequel/dataset/actions.rb:47:in `all'
  /home/deepak/.rvm/gems/ruby-2.3.1@project/bundler/gems/spree-admin-insights-f864b16c976b/app/reports/spree/sales_performance_report.rb:77:in `generate'
  /home/deepak/.rvm/gems/ruby-2.3.1@project/bundler/gems/spree-admin-insights-f864b16c976b/app/services/spree/report_generation_service.rb:23:in `generate_report'
  /home/deepak/.rvm/gems/ruby-2.3.1@project/bundler/gems/spree-admin-insights-f864b16c976b/app/controllers/spree/admin/insights_controller.rb:15:in `show'
  actionpack (4.2.7.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.7.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.7.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.7.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.7.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.7.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.7.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.7.1) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.7.1) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
  xray-rails (0.2.0) lib/xray/middleware.rb:38:in `call'
  route_downcaser (1.1.4) lib/route_downcaser/downcase_route_middleware.rb:20:in `_call'
  route_downcaser (1.1.4) lib/route_downcaser/downcase_route_middleware.rb:9:in `call'
  bullet (4.14.7) lib/bullet/rack.rb:12:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `catch'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (1.6.5) lib/rack/etag.rb:24:in `call'
  rack (1.6.5) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.5) lib/rack/head.rb:13:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.7.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  airbrake (4.1.0) lib/airbrake/rails/middleware.rb:13:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  rack-contrib (1.4.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/headers.rb:16:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.5) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:16:in `_call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:12:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  rack (1.6.5) lib/rack/content_length.rb:15:in `call'
  thin (1.7.0) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.7.0) lib/thin/connection.rb:84:in `catch'
  thin (1.7.0) lib/thin/connection.rb:84:in `pre_process'
  thin (1.7.0) lib/thin/connection.rb:53:in `process'
  thin (1.7.0) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.2.1) lib/eventmachine.rb:194:in `run_machine'
  eventmachine (1.2.1) lib/eventmachine.rb:194:in `run'
  thin (1.7.0) lib/thin/backends/base.rb:73:in `start'
  thin (1.7.0) lib/thin/server.rb:162:in `start'
  rack (1.6.5) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.5) lib/rack/server.rb:286:in `start'
  railties (4.2.7.1) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.7.1) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.7.1) lib/rails/commands/commands_tasks.rb:75:in `tap'
  railties (4.2.7.1) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.7.1) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.7.1) lib/rails/commands.rb:17:in `<top (required)>'
  script/rails:6:in `require'
  script/rails:6:in `<main>'
```

**Comment by dsawa** [comment]
@deepakm-webonise 
Just a note. I made a fork with PR for postgresql support.
https://github.com/vinsol-spree-contrib/spree-admin-insights/pull/32

**Comment by bansalakhil** [comment]
@deepakm-webonise @dsawa we have a major rewrite of the extension. Along with PostgreSQL support it also display hourly, daily, monthly reports (based on time interval selected). You can give it a try.
